baseURL = "https://ood.tips/"
languageCode = "en-us"
title = "ood.tips"
copyright = "Anton Shabinskiy"
theme = "hugo-paper"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -100

  [[menu.main]]
    identifier = "basic"
    name = "Basic track"
    url = "/basic"
    weight = -130

  [[menu.main]]
    identifier = "advanced"
    name = "Advanced track"
    url = "/advanced"
    weight = -120

  [[menu.main]]
    parent = "basic"
    name = "Tutorial"
    url = "/basic/tutorial/"
    weight = -110

  [[menu.main]]
    parent = "basic"
    name = "Glossary"
    url = "/basic/glossary/"
    weight = -100

  [[menu.main]]
    name = "University course"
    url = "/naukma/"
    weight = -90
