baseURL = "https://ood.tips/"
languageCode = "en-us"
title = "ood.tips"
copyright = "Anton Shabinskiy"
theme = "hugo-paper"
[menu]
  [[menu.main]]
    name = "Tutorial"
    url = "/tutorial/"
    weight = -140

  [[menu.main]]
    name = "Glossary"
    url = "/glossary/"
    weight = -130

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -120

  [[menu.main]]
    name = "University course"
    url = "/naukma/"
    weight = -110

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -100
